# Generated by Django 4.2.5 on 2023-09-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cat', models.IntegerField()),
                ('nombre_cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_eva', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_pmyac', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_resp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rec', models.IntegerField()),
                ('recomendacion', models.TextField()),
                ('meta', models.TextField()),
                ('plazo_cumplimiento', models.DateTimeField(auto_now_add=True, null=True)),
                ('indicador_validacion', models.CharField(max_length=255)),
                ('acciones_meta', models.TextField()),
                ('recursos', models.TextField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Obcervacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obcervacion', models.TextField()),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recomendacion')),
            ],
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_eje', models.IntegerField()),
                ('nombre_eje', models.CharField(max_length=255)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eje'),
        ),
    ]
