# Generated by Django 4.2.5 on 2023-09-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_evaluacion_responsable_recomendacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='nombre',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
