# Generated by Django 4.2.5 on 2023-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evaluacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_eva',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_pmyac',
            field=models.DateTimeField(null=True),
        ),
    ]
