# Generated by Django 4.2.5 on 2023-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_evaluacion_fecha_eva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
